### ISSUE TITLE
Same problem 

### ISSUE THREAD

**Issue by rswethashankar92** [inthehand/32feet#223] opened 2022-09-29 08:21 UTC
When i try to connect using IntheHand.net.bluetooth Bluetoothclient. I get an exception.
`client.BeginConnect(endPoint, new AsyncCallback(ConnectCB), client)
`
I get null reference exception.

What might be causing the exception?

_Originally posted by @AsfandNadeem in https://github.com/inthehand/32feet/issues/51#issuecomment-908246550_

**Comment by peterfoot** [comment] 2022-10-10 10:42
Closing as duplicate of #51

**Closed by peterfoot** 2022-10-10 10:42 UTC
