### ISSUE TITLE
{0} parameter error\ The device id provided is not a valid Bluetooth device object. "}

### ISSUE THREAD

**Issue by bbhxwl** [inthehand/32feet#137] opened 2021-07-21 04:37 UTC
{0} parameter error\ The device id provided is not a valid Bluetooth device object. "}

**Comment by stephen-systemfriend** [comment] 2021-07-21 08:47
duplicate of #134

**Comment by peterfoot** [comment] 2021-07-21 08:54
Closed as duplicate

**Closed by peterfoot** 2021-07-21 08:54 UTC
