### ISSUE TITLE
Bluetooth LE    When can I scan asynchronously? It takes 30s to scan the software now, which is too slow to use.

### ISSUE THREAD

**Issue by bbhxwl** [inthehand/32feet#207] opened 2022-07-08 07:50 UTC
When can I scan asynchronously? It takes 30s to scan the software now, which is too slow to use.

**Comment by bbhxwl** [comment] 2022-07-16 02:09
Can we consider making a more practical Bluetooth ble for scanning?

**Comment by peterfoot** [comment] 2022-09-11 12:34
Closing as duplicate of #182

**Closed by peterfoot** 2022-09-11 12:34 UTC
